##  Fase de Limpieza y Preprocesamiento de Datos
Tras la exploración inicial (EDA), procedemos a la limpieza del dataset `the_office_series.csv`. 
El objetivo es eliminar variables con baja representatividad estadística y normalizar los tipos 
de datos para facilitar las visualizaciones finales.

In [1]:
# Importación de librerías

import pandas as pd
import numpy as np

# Configuración para visualizar todas las columnas del DataFrame
pd.set_option('display.max_columns', None)

In [2]:
df_series = pd.read_csv("files/the_office_series.csv", index_col=0)

df_series.head()

,Season,EpisodeTitle,About,Ratings,Votes,Viewership,Duration,Date,GuestStars,Director,Writers
0,1,Pilot,The premiere episode introduces the boss and s...,7.5,4936,11.2,23,24 March 2005,NaN,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels
1,1,Diversity Day,Michael's off color remark puts a sensitivity ...,8.3,4801,6.0,23,29 March 2005,NaN,Ken Kwapis,B. J. Novak
2,1,Health Care,Michael leaves Dwight in charge of picking the...,7.8,4024,5.8,22,5 April 2005,NaN,Ken Whittingham,Paul Lieberstein
3,1,The Alliance,"Just for a laugh, Jim agrees to an alliance wi...",8.1,3915,5.4,23,12 April 2005,NaN,Bryan Gordon,Michael Schur
4,1,Basketball,Michael and his staff challenge the warehouse ...,8.4,4294,5.0,23,19 April 2005,NaN,Greg Daniels,Greg Daniels

### Gestión de Variables con Nulos
Durante el análisis de calidad, detectamos que la columna `GuestStars` presentaba un **84.57% de valores nulos**. 
Dado que esta variable no es central para nuestro análisis de éxito comercial (audiencia) y 
percepción de calidad (IMDb), hemos decidido **dropearla** para simplificar el modelo de datos 
y evitar ruidos en las futuras agrupaciones.

In [3]:
df_series.drop(columns=["GuestStars"], inplace=True)

In [4]:
df_series.to_csv('the_office_series.csv')

In [5]:
df_series.head()

,Season,EpisodeTitle,About,Ratings,Votes,Viewership,Duration,Date,Director,Writers
0,1,Pilot,The premiere episode introduces the boss and s...,7.5,4936,11.2,23,24 March 2005,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels
1,1,Diversity Day,Michael's off color remark puts a sensitivity ...,8.3,4801,6.0,23,29 March 2005,Ken Kwapis,B. J. Novak
2,1,Health Care,Michael leaves Dwight in charge of picking the...,7.8,4024,5.8,22,5 April 2005,Ken Whittingham,Paul Lieberstein
3,1,The Alliance,"Just for a laugh, Jim agrees to an alliance wi...",8.1,3915,5.4,23,12 April 2005,Bryan Gordon,Michael Schur
4,1,Basketball,Michael and his staff challenge the warehouse ...,8.4,4294,5.0,23,19 April 2005,Greg Daniels,Greg Daniels

### Creación de Dataset Sintético de Escenarios
Para analizar la distribución espacial de la serie, hemos generado un dataset basado en la 
frecuencia de aparición y relevancia de los sets de rodaje. 
* **Nota técnica:** Las "Escenas Aproximadas" y los "Porcentajes" se han normalizado para 
    sumar el 100% de la actividad principal capturada en el documental.

In [6]:
# Datos basados en la frecuencia de aparición y relevancia de los sets de rodaje de la serie
data = {
    "Escenario": [
        "Oficina Principal (Open Space)", 
        "Despacho del Gerente (Michael/Andy)", 
        "Sala de Juntas (Conference Room)", 
        "Cocina / Zona de Descanso", 
        "Recepción", 
        "El Anexo (Toby, Kelly, Gabe)", 
        "Almacén (Warehouse)", 
        "Zona de Contabilidad",
        "Localizaciones Externas (Schrute Farms, Scranton, etc.)"
    ],
    "Escenas_Aproximadas": [4180, 1400, 1115, 745, 560, 465, 465, 370, 195],
    "Porcentaje": ["44.2", "14.8", "11.8", "7.9", "5.9", "4.9", "4.9", "3.9", "2.1"]
}

df = pd.DataFrame(data)

# Guardar a CSV
df.to_csv('the_office_scenario.csv', index=False, encoding='utf-8-sig')

###  Resumen de la Fase de Limpieza:
1.  **Reducción de dimensionalidad:** Eliminación de la columna `GuestStars`.
2.  **Persistencia:** Los datos limpios se han exportado a `the_office_series.csv` y 
    `the_office_scenario.csv` para asegurar que las visualizaciones usen datos depurados.
3.  **Integridad:** Se mantiene el total de **188 episodios** con todas sus métricas críticas 
    (Ratings, Votes, Viewership) intactas.